#######################################################
# This is the main CI workflow test
#######################################################
name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test
  Test:
    # The type of runner that the job will run on: ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checksout action repository under $GITHUB_WORKSPACE
      - name: Checkout action repository
        uses: actions/checkout@v3

      # Run checkout this repository to path 'myself'
      - name: Checkout this repository
        uses: ./
        with:
          path: myself
          ref: ${{ github.ref }}
        
      # Run checkout an extern example repository to 'extern'
      - name: Checkout an extern repository
        uses: ./
        with:
          repository: githubtraining/community-contributors
          path: extern
          ref: main

      # Run checkout an git lfs example repository to folder 'git-lfs'
      - name: Checkout a git-lfs repository
        uses: ./
        with:
          repository: Apress/repo-with-large-file-storage
          path: git-lfs
          ref: master
          lfs: true

      # Run checkout this repository to path 'myself-alt-ref-default' to choose default branch
      - name: Checkout this repository at alternative reference
        uses: ./
        with:
          path: myself-alt-ref-default
          ref: not/existing/feature/branch
        
      # Run checkout this repository to path 'myself-alt-ref-branch' to choose an explicit alternative branch
      - name: Checkout this repository at alternative reference (branch)
        uses: ./
        with:
          path: myself-alt-ref-branch
          ref: not/existing/feature/branch
          alt_ref: develop

      # Run checkout this repository to path 'myself-alt-ref-tag' to choose an explicit alternative tag
      - name: Checkout this repository at alternative reference (tag)
        uses: ./
        with:
          path: myself-alt-ref-tag
          ref: not/existing/feature/branch
          alt_ref: v0.1

      # Run checkout this repository with own action (last deployed)
      - name: Checkout this repository at alternative reference (tag)
        uses: rohmanngmbh/action-checkout@v0.1
        with:
          path: myself-action

      # List folder recursive (only for debugging)
      - name: List folders
        run: |
          ls -R
    